export const userData = [
  {
    firstName: "Andrew",
    lastName: "Baker",
    major: "Computer Science",
    year: "Sophomore",
    college: "Engineering",
    picture: {
      uri: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg",
    },
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    clubs: ["V1", "Alpha Epsilon Pi", "Best Buddies of Ann Arbor"],
    experiences: ["Google", "Amazon"],
    courses: ["EECS 281", "EECS 203", "CHEM 130", "CHEM 125", "EECS 280"],
  },
  {
    firstName: "Emily",
    lastName: "Jennett",
    major: "Art + UX Design",
    year: "Sophomore",
    college: "School of Information",
    picture: {
      uri: "https://images.pexels.com/photos/806835/pexels-photo-806835.jpeg?auto=compress&cs=tinysrgb&w=800",
    },
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    clubs: ["V1", "Kappa Theta Pi", "SHEI Magazine"],
    experiences: ["Figma", "Microsoft"],
    courses: ["EECS 281", "EECS 203", "CHEM 130", "CHEM 125", "EECS 280"],
  },
  {
    firstName: "Alison",
    lastName: "Roeda",
    major: "Business",
    year: "Freshman",
    college: "Ross School of Business",
    picture: { uri: "https://picsum.photos/200/378" },
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    clubs: ["V1", "Tech for Social Good"],
    experiences: ["Amazon", "WhoU"],
    courses: ["BA 100", "EECS 203", "CHEM 130", "CHEM 125", "EECS 280"],
  },
  {
    firstName: "Griffin",
    lastName: "Coolidge",
    major: "Mechanical Engineering",
    year: "Freshman",
    college: "Ross School of Business",
    picture: { uri: "https://picsum.photos/205/302" },
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    clubs: ["V1", "Kappa Theta Pi"],
    experiences: ["Google", "Amazon"],
    courses: ["EECS 281", "EECS 203", "CHEM 130", "CHEM 125", "EECS 280"],
  },
  {
    firstName: "Connor",
    lastName: "Park",
    major: "Computer Science",
    year: "Freshman",
    college: "Engineering",
    picture: { uri: "https://picsum.photos/235/302" },
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    clubs: ["V1", "UpRound Ventures"],
    experiences: ["Palantir", "Apple"],
    courses: ["EECS 281", "EECS 203", "CHEM 130", "CHEM 125", "EECS 280"],
  },
  {
    firstName: "Emily",
    lastName: "Johnson",
    major: "Electrical Engineering",
    year: "Junior",
    college: "Engineering",
    picture: { uri: "https://picsum.photos/208/302" },
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    clubs: ["Engineering Society", "IEEE"],
    experiences: ["Microsoft", "Tesla"],
    courses: ["EECS 370", "EECS 373", "MATH 216", "PHYSICS 240", "ENGR 101"],
  },
  {
    firstName: "Sarah",
    lastName: "Smith",
    major: "Chemistry",
    year: "Sophomore",
    college: "Literature, Science, and Arts",
    picture: { uri: "https://picsum.photos/209/302" },
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    clubs: ["Chemistry Club", "STEM Ambassadors"],
    experiences: ["Johnson & Johnson", "Merck"],
    courses: ["CHEM 210", "CHEM 215", "MATH 115", "BIOL 171", "PHYSICS 135"],
  },
  {
    firstName: "Daniel",
    lastName: "Taylor",
    major: "Mechanical Engineering",
    year: "Senior",
    college: "Engineering",
    picture: { uri: "https://picsum.photos/210/302" },
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    clubs: ["ASME", "Robotics Club"],
    experiences: ["Boeing", "Lockheed Martin"],
    courses: [
      "MECHENG 360",
      "MECHENG 420",
      "ENGR 100",
      "MATH 216",
      "PHYSICS 240",
    ],
  },
  {
    firstName: "Grace",
    lastName: "Walker",
    major: "Mathematics",
    year: "Junior",
    college: "Literature, Science, and Arts",
    picture: { uri: "https://picsum.photos/211/302" },
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    clubs: ["Math Club", "STEM Women"],
    experiences: ["IBM", "Intel"],
    courses: ["MATH 217", "MATH 316", "CSCS 423", "PHYSICS 235", "STATS 250"],
  },
  {
    firstName: "Olivia",
    lastName: "Clark",
    major: "Biomedical Engineering",
    year: "Sophomore",
    college: "Engineering",
    picture: { uri: "https://picsum.photos/212/302" },
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    clubs: ["Biomed Society", "Health Innovators"],
    experiences: ["Medtronic", "Johnson & Johnson"],
    courses: ["BIOMEDE 221", "BIOMEDE 231", "CHEM 125", "MATH 116", "ENGR 151"],
  },
  {
    firstName: "Michael",
    lastName: "Jones",
    major: "Business Administration",
    year: "Senior",
    college: "Ross School of Business",
    picture: { uri: "https://picsum.photos/220/302" },
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    clubs: ["Business Leaders Club", "Finance Society"],
    experiences: ["Goldman Sachs", "JP Morgan"],
    courses: [
      "BUSINESS 301",
      "FIN 350",
      "MARKETING 320",
      "STRATEGY 400",
      "STATS 412",
    ],
  },
  {
    firstName: "Hannah",
    lastName: "Miller",
    major: "Psychology",
    year: "Sophomore",
    college: "Literature, Science, and Arts",
    picture: { uri: "https://picsum.photos/225/302" },
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    clubs: ["Psychology Club", "Mindfulness Society"],
    experiences: ["Psychological Research Lab", "Therapy Assistant Volunteer"],
    courses: ["PSYCH 111", "PSYCH 230", "SOC 100", "ANTHRO 101", "STATS 250"],
  },
  {
    firstName: "Ethan",
    lastName: "Davis",
    major: "Mechanical Engineering",
    year: "Junior",
    college: "Engineering",
    picture: { uri: "https://picsum.photos/230/302" },
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    clubs: ["ASME", "Robotics Club"],
    experiences: ["NASA", "SpaceX"],
    courses: [
      "MECHENG 360",
      "MECHENG 420",
      "ENGR 100",
      "MATH 216",
      "PHYSICS 240",
    ],
  },
  {
    firstName: "Emma",
    lastName: "Harrison",
    major: "Communications",
    year: "Senior",
    college: "Communication and Media",
    picture: { uri: "https://picsum.photos/235/302" },
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    clubs: ["Media Society"],
    experiences: ["CNN", "PR Agency"],
    courses: ["COMM 101", "COMM 320", "JOURN 300", "ADPR 400", "FILM 250"],
  },
];
